config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root to: 'pages#home'
  get '/htmlsafe', to: 'htmlsafe#index'
  resources :links, only: %i[index create]
  resources :users, only: %i[index create]
  resources :products, only: %i[index]
  post "/csp-violation-report", to: "csp_reports#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if verify && @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body)
    end

    def verify
      verified = Turnstile.verify(token: params['cf-turnstile-response'] , ip: request.remote_ip)
      flash[:alert] = "Vous êtes une machine" unless verified
      verified
    end
end

app/controllers/csp_reports_controller.rb
class CspReportsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    report = request.body.read

    Rails.logger.info("CSP violation: #{report}")

    head :no_content
  end
end

app/controllers/htmlsafe_controller.rb
class HtmlsafeController < ApplicationController
  def index
    @html_content = "<strong>This is bold text</strong>"
    @links = Link.all
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
    @link = Link.new
  end

  def create
    target = link_params[:target].start_with?('www') ? "https://#{link_params[:target]}" : link_params[:target]
    Link.create(target:)

    redirect_to links_path
  end

  private

  def link_params
    params.require(:link).permit(:target)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    # Vulnerable query that directly uses user input in SQL query
    @unsafe_products = search_unsafe_products(params[:query])

    # ActiveRecord's built-in query methods to sanitize user inputs
    @safe_products = search_safe_products(params[:query])
  end

  private

  def search_unsafe_products(query)
    return [] unless query.present?

    Product.where("LOWER(name) LIKE '%#{query.downcase}%'")
  end

  def search_safe_products(query)
    return [] unless query.present?

    Product.where("LOWER(name) LIKE ?", "%#{query.downcase}%")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :index
    end
  end

  private

  def user_params
    params[:user].permit! # Permitting all parameters
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= comment.body %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this comment", comment, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this comment", edit_comment_path(comment), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, class: "contents") do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%= tag.div data: { controller: :turnstile, turnstile_site_key_value: Rails.application.credentials.dig(:turnstile_site_key)} %>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing comment</h1>

  <%= render "form", comment: @comment %>

  <%= link_to "Show this comment", @comment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to comments", comments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/comments/index.html.erb
<div class="m-4 pt-10 px-4">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Comments</h1>
    <%= link_to "New comment", new_comment_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="comments" class="min-w-full">
    <%= render @comments %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="m-4 pt-10 mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New comment</h1>

  <%= render "form", comment: @comment %>

  <%= link_to "Back to comments", comments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/comments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @comment %>

    <%= link_to "Edit this comment", edit_comment_path(@comment), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this comment", comment_path(@comment), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to comments", comments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/htmlsafe/index.html.erb
<%= content_for :header_link do %>
  <a href="https://apidock.com/rails/String/html_safe" target="blank" class="text-sm font-semibold leading-6 text-gray-900">Plus d'info <span aria-hidden="true">&rarr;</span></a>
<% end %>

<div class="bg-white px-6 py-6 sm:py-6 lg:px-8">
  <div class="mx-auto max-w-2xl text-center">
    <h3 class="text-4xl font-bold tracking-tight text-gray-900">Méthode html_safe avec Rails</h3>
    <p class="mt-6 text-lg leading-8 text-gray-600">Marque une chaîne comme sécurisée de confiance. Il sera inséré dans HTML sans qu'aucun échappement supplémentaire ne soit effectué.</p>
  </div>
</div>
<div class="bg-white shadow sm:rounded-lg flex justify-center">
  <div class="px-4 py-5 sm:p-6">
    <div class="mt-2 max-w-xl text-sm text-gray-500">
      <p>Imaginons que nous ayons besoin de créer une string avec des balises pour notre vue comme par exemple <code><%= @html_content %></code></p>
    </div>
  </div>
</div>

<div class="flex flex-col items-center p-4 my-4 gap-2 border-b-2">
  <h3 class="text-base font-semibold leading-6 text-gray-900 my-2">Sans html_safe</h3>
  <p><%= @html_content %></p>
  <h3 class="text-base font-semibold leading-6 text-gray-900 my-2">Avec html_safe</h3>
  <p><%= @html_content.html_safe %></p>
</div>

<details class="p-4 my-4">
  <summary>Pour aller plus loin</summary>
  <div class="border-b flex flex-col items-center border-gray-200 bg-white px-4 py-5 sm:px-6">
    <h3 class="text-base font-semibold leading-6 text-gray-900">Pour info, par défaut rails "échappe" automatiquement le contenu</h3>
    <p class="mt-1 text-sm text-gray-500">Exemple avec nos liens précedents</p>
  </div>
  <% if @links.any? %>
    <div class="flex flex-col items-center gap-2">
      <% @links.each do |link| %>
        <p><%= link.target %></p>
      <% end %>
    </div>
  <% else %>
    <%= link_to 'Commencez par créer un lien', links_path, class: "mt-1 truncate text-xs leading-5 text-gray-500"%>
  <% end %>
</details>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CyberSecurityTraining</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag %>
    <script src="https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onloadTurnstileCallback" defer></script>
  </head>

  <body class="h-full font-sans antialiased font-normal leading-normal bg-white">
    <div class="main flex flex-col">
      <%= render partial: "shared/flash" %>
      <%= render "shared/header" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/_safe_link.html.erb
<li class="flex items-center justify-between gap-x-6 py-5">
  <div class="flex min-w-0 gap-x-4">
    <div class="min-w-0 flex-auto">
      <div class="flex items-start gap-x-3">
        <p class="text-sm font-semibold leading-6 text-gray-900">With sanitizing</p>
        <p class="rounded-md whitespace-nowrap mt-0.5 px-1.5 py-0.5 text-xs font-medium ring-1 ring-inset text-green-700 bg-green-50 ring-green-600/20">Safe</p>
      </div>
      <p class="mt-1 truncate text-xs leading-5 text-gray-500">Created at <time datetime="2023-03-17T00:00Z"><%= link.created_at %></time></p>
    </div>
  </div>
  <p class="rounded-full bg-white px-2.5 py-1 text-xs font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
    <%= sanitize(link_to("Test it!", link.target)) %>
  </p>
</li>

app/views/links/_unsafe_link.html.erb
<li class="flex items-center justify-between gap-x-6 py-5">
  <div class="flex min-w-0 gap-x-4">
    <div class="min-w-0 flex-auto">
      <div class="flex items-start gap-x-3">
        <p class="text-sm font-semibold leading-6 text-gray-900">Without sanitizing</p>
        <p class="rounded-md whitespace-nowrap mt-0.5 px-1.5 py-0.5 text-xs font-medium ring-1 ring-inset text-red-700 bg-red-50 ring-red-600/20">Danger</p>
      </div>
      <p class="mt-1 truncate text-xs leading-5 text-gray-500">Created at <time datetime="2023-03-17T00:00Z"><%= link.created_at %></time></p>
    </div>
  </div>
  <%= link_to "Test it!", link.target, class:"rounded-full bg-white px-2.5 py-1 text-xs font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"%>
</li>

app/views/links/index.html.erb
<%= content_for :header_link do %>
  <a href="https://owasp.org/www-community/attacks/xss/" target="blank" class="text-sm font-semibold leading-6 text-gray-900">Plus d'info <span aria-hidden="true">&rarr;</span></a>
<% end %>

<div class="bg-white px-6 py-12 sm:py-12 lg:px-8">
  <div class="mx-auto max-w-2xl text-center">
    <h3 class="text-4xl font-bold tracking-tight text-gray-900">Cross-Site Scripting (XSS)</h3>
    <p class="mt-6 text-lg leading-8 text-gray-600">Il s'agit d'une vulnérabilité permettant aux attaquants d'injecter du code nuisible dans un site web. Ce code s'exécute dans le navigateur d'une victime, ce qui peut entraîner le vol de données sensibles telles que les informations de connexion</p>
    <p class="mt-6 text-lg leading-8 text-gray-600">La prévention des XSS implique de nettoyer le contenu généré par les utilisateurs. Exemple essayez <code>sanitize(link_to("Click!", target))</code></p>
  </div>
</div>

<div class="bg-white shadow sm:rounded-lg flex justify-center">
  <div class="px-4 py-5 sm:p-6">
    <div class="mt-2 max-w-xl text-sm text-gray-500">
      <p>Essayez avec JS code: <code>javascript:alert('XSS Attack!')</code></p>
    </div>
    <%= form_with model: @link, class:"mt-5 sm:flex sm:items-center" do |form| %>
      <div class="w-full sm:max-w-xs">
          <%= form.label :target, "target",  class:"sr-only" %>
          <%= form.text_field :target, placeholder:"your injection!" , class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"%>
      </div>
      <%= form.button "Enregistrer", class: "mt-3 inline-flex w-full items-center justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 sm:ml-3 sm:mt-0 sm:w-auto" %>
    <% end %>
  </div>
</div>

<div class="max-w-4xl  mx-auto p-4 my-8">
  <div class="border-b border-gray-200 bg-white px-4 py-5 sm:px-6">
    <h3 class="text-base font-semibold leading-6 text-gray-900">Links</h3>
    <p class="mt-1 text-sm text-gray-500">Liste de vos liens.</p>
  </div>
  <% if @links.any? %>
    <ul role="list" class="divide-y divide-gray-100">
      <% @links.each do |link| %>
        <%= render "safe_link", link: link %>
        <%= render "unsafe_link", link: link %>
      <% end %>
    </ul>
  <% else %>
    <p class="mt-1 truncate text-xs leading-5 text-gray-500">Commencez par créer un lien</p>
  <% end %>
</div>

app/views/pages/_link.html.erb
<li class="relative flex items-center space-x-4 py-4">
  <div class="min-w-0 flex-auto">
    <div class="flex items-center gap-x-3">
      <h2 class="min-w-0 text-sm font-semibold leading-6">
        <span class="whitespace-nowrap"><%= title %></span>
      </h2>
    </div>
    <div class="mt-3 gap-x-2.5 text-xs leading-5 text-gray-400">
      <p class="whitespace-nowrap"><%= subtitle %></p>
    </div>
  </div>
  <div class="rounded-full flex-none py-1 px-2 text-xs font-medium ring-1 ring-inset text-gray-400 bg-gray-400/10 ring-gray-400/20">Easy</div>
  <svg class="h-5 w-5 flex-none text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
  </svg>
</li>

app/views/pages/home.html.erb
<div class="bg-white">
  <div class="relative isolate px-6 lg:px-8">
    <div class="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80" aria-hidden="true">
      <div class="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
    <div class="mx-auto max-w-2xl py-8 sm:py-16 lg:py-32">
      <div class="text-center">
        <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">RoR cybersécurité</h1>
        <p class="mt-6 text-lg leading-8 text-gray-600">Mieux sécuriser vos applications Ruby on Rails !</p>
        <div class="mt-10 flex items-center justify-center gap-x-6">
          <a href="https://owasp.org/" target="blank class="text-sm font-semibold leading-6 text-gray-900">Voir plus sur OWASP <span aria-hidden="true">→</span></a>
        </div>
      </div>
    </div>
    <div class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]" aria-hidden="true">
      <div class="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
    <div class="flex justify-center">
      <ul role="list" class="divide-y divide-white/5 w-80">
        <%= link_to links_path do %>
          <%= render "link", title: "Xss", subtitle: "Injecter du javascript malveillant" %>
        <% end %>
        <%= link_to htmlsafe_path do %>
          <%= render "link", title: "HTML safe", subtitle: "Quand et comment utiliser html safe" %>
        <% end %>
        <%= link_to users_path do %>
          <%= render "link", title: "Params", subtitle: "Tirez parti d'un filtrage des paramètres" %>
        <% end %>
        <%= link_to products_path do %>
          <%= render "link", title: "Injection SQL", subtitle: "Injecter une requête malveillante" %>
        <% end %>
        <%= link_to comments_path do %>
          <%= render "link", title: "Turnstile", subtitle: "Alternative au Captcha" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/products/_product.html.erb
<div class="<%= class_names(color, 'text-center') %>">
  <p class="bold"><%= product.name %></p>
</div>

app/views/products/index.html.erb
<div class="bg-white px-6 py-12 sm:py-12 lg:px-8">
  <div class="mx-auto max-w-2xl text-center">
    <h3 class="text-4xl font-bold tracking-tight text-gray-900">Injection SQL</h3>
    <p class="mt-6 text-lg leading-8 text-gray-600">En exploitant cette vulnérabilité, les attaquants peuvent manipuler les requêtes SQL exécutées et potentiellement obtenir un accès non autorisé à des données sensibles</p>
    <p class="mt-6 text-lg leading-8 text-gray-600">On peut s'en protéger en utilisant les méthodes de requête intégrées d'ActiveRecord et empêcher les injections SQL. Exemple d'utilisation <code>where("name LIKE ?", "%#{search_query}%")</code></p>
  </div>
</div>

<div class="bg-white shadow sm:rounded-lg flex justify-center">
  <div class="px-4 py-5 sm:p-6">
    <div class="mt-2 max-w-xl text-sm text-gray-500">
      <p>Lancez les seeds en premier ! Soumettez ensuite une requête simple comme Apple ou malveillante comme <code>' OR '1'='1</code></p>
    </div>
    <%= form_with url: products_path, method: :GET, class:"mt-5 sm:flex sm:items-center" do |form| %>
      <div class="w-full sm:max-w-xs">
          <%= form.label :query, "unsafe query",  class:"sr-only" %>
          <%= form.text_field :query, value:  params[:query], placeholder:"your injection!" , class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
      </div>
      <%= form.button "soumettre", class: "mt-3 inline-flex w-full items-center justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 sm:ml-3 sm:mt-0 sm:w-auto" %>
    <% end %>
  </div>
</div>

<div class="flex flex-col justify-content p-4 my-8">
  <div class=" flex flex-col items-center bg-white px-4 py-5 sm:px-6">
    <h3 class="text-base font-semibold leading-6 text-gray-900">Produits</h3>
    <p class="mt-1 text-sm text-gray-500">Liste de vos Produits.</p>
  </div>
  <div class="flex">
    <div class="flex-1">
      <p class="text-center border-b border-gray-200">Vous êtes en sécurité</p>
      <% if @safe_products.any? %>
        <ul role="list" class="divide-y divide-gray-100">
          <% @safe_products.each do |safe_product| %>
            <%= render "product", product: safe_product, color: "bg-green-50" %>
          <% end %>
        </ul>
      <% else %>
        <p class="mt-1 truncate text-xs leading-5 text-gray-500">Soumettez une requête</p>
      <% end %>
    </div>
    <div class="flex-1">
      <p class="text-center border-b border-gray-200">Vous êtes en danger</p>
      <% if @unsafe_products.any? %>
        <ul role="list" class="divide-y divide-gray-100">
          <% @unsafe_products.each do |unsafe_product| %>
            <%= render "product", product: unsafe_product, color: "bg-red-50" %>
          <% end %>
        </ul>
      <% else %>
        <p class="mt-1 truncate text-xs leading-5 text-gray-500">Soumettez une requête</p>
      <% end %>
    </div>
  </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header class="absolute inset-x-0 top-0 z-50">
    <nav class="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
      <div class="flex lg:flex-1">
        <%= link_to root_path, class:"-m-1.5 p-1.5" do %>
          <span class="sr-only">Rails security training</span>
          <%= image_tag "lock.png", class: "h-8 w-auto" %>
        <% end %>
      </div>
      <div class="hidden lg:flex lg:flex-1 lg:justify-end">
        <%= yield :header_link %>
      </div>
    </nav>
</header>

app/views/users/_user.html.erb
<li class="flex justify-between gap-x-6 py-5">
  <div class="flex min-w-0 gap-x-4">
    <% avatar = user.admin ? "admin.png" : "joker.png" %>
    <%= image_tag avatar, class: "h-12 w-12 flex-none rounded-full bg-gray-50" %>
    <div class="min-w-0 flex-auto">
      <p class="text-sm font-semibold leading-6 text-gray-900"><%= user.username %></time></p>
      <p class="mt-1 truncate text-xs leading-5 text-gray-500"><%= user.email %></time></p>
    </div>
  </div>
  <div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
    <p class="text-sm leading-6 text-gray-900"><%= user.admin ? "Admin" : "Regular" %></time></p>
    <p class="mt-1 text-xs leading-5 text-gray-500">Created at <time datetime="2023-03-17T00:00Z"><%= user.created_at %></time></p>
  </div>
</li>